### ISSUE TITLE
Does not support Quaternion rotation

### ISSUE THREAD

**Issue by Marslettuce** [j3soon/blender-highlight-channels#1]
Unless I'm mistaken, there's no way to use this for quaternions.

**Comment by j3soon** [comment]
Yes, no support for quaternions in the current version.

We do support quaternions in a early testing version (unreleased). However, after discussing with [@chickenfishoil](https://www.youtube.com/@chickenfishoil), we think this feature may not be used frequently, and therefore dropped it.

It's quite simple to add back the support for quaternions in the next version, but we also need to figure out the hotkey for highlighting the 4 quaternion curves.

Could you share your use cases and preferred hotkeys for highlighting quaternions? Thank you!

**Comment by Marslettuce** [comment]
Quaternions can be vital for avoiding gimbal lock. One example here: https://youtu.be/z3dDsz4f20A?si=PCCXY4iwsQt50N6c&t=147
This is a very common problem in animation, and is the primary use-case for quaternions.

Ideally, the same hotkeys for Euler channels would apply when you switch to Quaternion, but I'm not sure how feasible that is. Alternatively, Alt + Shift + Q/W/E/R would be acceptable, I think. 

Thanks for all the work you guys have done, it's very much appreciated.

**Comment by j3soon** [comment]
Could you provide a screen recording of your current workflow? A quick demonstration of your need on highlighting one of Quaternion X/Y/Z/W channels and adjusting the curve will be very appreciated. After learning your workflow, I can try think of the best way to include this feature.

Although I'm aware of the benefits of quaternions, I thought the current animation industry still often use Euler angles, since the curves are more intuitive. If there are animators adjusting animation curves using quaternions, then I would want to add back this feature.

Currently, my thought is to use `Alt` + {`A`, `S`, `D`, `F`} for Quaternion X/Y/Z/W channels, and replace the current toggle hotkey `Alt` + `F` with `Alt` + `V`. We can use the same hotkeys as Euler X/Y/Z since only one rotation system will be adopted per curve.

**Comment by Karolin-a** [comment]
i double that - recently moved to blender from maya for a project and all rotations in the rig are set to quaternion as default. I initially converted all to euler as that's what i'm used to, but got some gimbal locks reasonably quickly, which made me think 'well, there must be a reason the quaternions were used'. After some research into them, I'd love to drop euler, but the lack of ability to highlight the channels as easily is frustrating. It would be great if there were a switch or even just an alternate version of the script that would support the same shortcuts for quaternion X,Y and Z rotations (as mentioned above)

**Comment by j3soon** [comment]
Hi @Marslettuce and @Karolin-a,

I've just released v0.0.3 that supports highlighting Quaternions. Please try it out.

After some discussion with [@chickenfishoil](https://www.youtube.com/@chickenfishoil), we chose `Alt` + `Shift` + {`A`, `S`, `D`, `F`} for Quaternion W/X/Y/Z.
- This prevents hotkey conflict when using Euler angles and Quaternions simultaneously (and allow backward compatibility).
- In addition, we follow the convention WXYZ (instead of XYZW) in Blender for the hotkey order.

It would also be helpful if you could provide a screen recording of your workflow for others to refer to in the future.

**Comment by Karolin-a** [comment]
Hi @j3soon!
Thanks so much, just tested and works perfectly.
Will see how the shift+alt combo works, will probs take some getting used to, but as is, this is very helpful, thank you!
Due to the nature of the project I'm on just now, I cannot record the workflow, but when I'm doing something that can be shared, I'll be happy to help out here :)
